# Build Stage
ARG NODE_VERSION=20.9.0

FROM node:${NODE_VERSION}-alpine as build

ARG FRONTEND_HOST=localhost
ARG BACKEND_HOST=localhost
ARG FRONTEND_PORT=8888
ARG BACKEND_PORT=8091

ENV REACT_APP_SERVER_BASE_URL=http://${BACKEND_HOST}:${BACKEND_PORT}
ENV REACT_APP_WS_BASE_URL=ws://${FRONTEND_HOST}:${FRONTEND_PORT}
ENV NODE_ENV=production
ENV PUBLIC_URL=http://${FRONTEND_HOST}:${FRONTEND_PORT}

WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Nginx webserver Stage
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD [ "nginx", "-g", "daemon off;" ]